# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sdic/multicast

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sdic/multicast

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sdic/multicast/CMakeFiles /home/sdic/multicast/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sdic/multicast/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tcp

# Build rule for target.
tcp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tcp
.PHONY : tcp

# fast build rule for target.
tcp/fast:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/build
.PHONY : tcp/fast

src/buffer/cmd_buffer.o: src/buffer/cmd_buffer.cpp.o

.PHONY : src/buffer/cmd_buffer.o

# target to build an object file
src/buffer/cmd_buffer.cpp.o:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/buffer/cmd_buffer.cpp.o
.PHONY : src/buffer/cmd_buffer.cpp.o

src/buffer/cmd_buffer.i: src/buffer/cmd_buffer.cpp.i

.PHONY : src/buffer/cmd_buffer.i

# target to preprocess a source file
src/buffer/cmd_buffer.cpp.i:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/buffer/cmd_buffer.cpp.i
.PHONY : src/buffer/cmd_buffer.cpp.i

src/buffer/cmd_buffer.s: src/buffer/cmd_buffer.cpp.s

.PHONY : src/buffer/cmd_buffer.s

# target to generate assembly for a file
src/buffer/cmd_buffer.cpp.s:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/buffer/cmd_buffer.cpp.s
.PHONY : src/buffer/cmd_buffer.cpp.s

src/buffer/header_buffer.o: src/buffer/header_buffer.cpp.o

.PHONY : src/buffer/header_buffer.o

# target to build an object file
src/buffer/header_buffer.cpp.o:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/buffer/header_buffer.cpp.o
.PHONY : src/buffer/header_buffer.cpp.o

src/buffer/header_buffer.i: src/buffer/header_buffer.cpp.i

.PHONY : src/buffer/header_buffer.i

# target to preprocess a source file
src/buffer/header_buffer.cpp.i:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/buffer/header_buffer.cpp.i
.PHONY : src/buffer/header_buffer.cpp.i

src/buffer/header_buffer.s: src/buffer/header_buffer.cpp.s

.PHONY : src/buffer/header_buffer.s

# target to generate assembly for a file
src/buffer/header_buffer.cpp.s:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/buffer/header_buffer.cpp.s
.PHONY : src/buffer/header_buffer.cpp.s

src/global/global.o: src/global/global.cpp.o

.PHONY : src/global/global.o

# target to build an object file
src/global/global.cpp.o:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/global/global.cpp.o
.PHONY : src/global/global.cpp.o

src/global/global.i: src/global/global.cpp.i

.PHONY : src/global/global.i

# target to preprocess a source file
src/global/global.cpp.i:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/global/global.cpp.i
.PHONY : src/global/global.cpp.i

src/global/global.s: src/global/global.cpp.s

.PHONY : src/global/global.s

# target to generate assembly for a file
src/global/global.cpp.s:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/global/global.cpp.s
.PHONY : src/global/global.cpp.s

src/listener.o: src/listener.cpp.o

.PHONY : src/listener.o

# target to build an object file
src/listener.cpp.o:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/listener.cpp.o
.PHONY : src/listener.cpp.o

src/listener.i: src/listener.cpp.i

.PHONY : src/listener.i

# target to preprocess a source file
src/listener.cpp.i:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/listener.cpp.i
.PHONY : src/listener.cpp.i

src/listener.s: src/listener.cpp.s

.PHONY : src/listener.s

# target to generate assembly for a file
src/listener.cpp.s:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/listener.cpp.s
.PHONY : src/listener.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/sender.o: src/sender.cpp.o

.PHONY : src/sender.o

# target to build an object file
src/sender.cpp.o:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/sender.cpp.o
.PHONY : src/sender.cpp.o

src/sender.i: src/sender.cpp.i

.PHONY : src/sender.i

# target to preprocess a source file
src/sender.cpp.i:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/sender.cpp.i
.PHONY : src/sender.cpp.i

src/sender.s: src/sender.cpp.s

.PHONY : src/sender.s

# target to generate assembly for a file
src/sender.cpp.s:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/sender.cpp.s
.PHONY : src/sender.cpp.s

src/task_queue.o: src/task_queue.cpp.o

.PHONY : src/task_queue.o

# target to build an object file
src/task_queue.cpp.o:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/task_queue.cpp.o
.PHONY : src/task_queue.cpp.o

src/task_queue.i: src/task_queue.cpp.i

.PHONY : src/task_queue.i

# target to preprocess a source file
src/task_queue.cpp.i:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/task_queue.cpp.i
.PHONY : src/task_queue.cpp.i

src/task_queue.s: src/task_queue.cpp.s

.PHONY : src/task_queue.s

# target to generate assembly for a file
src/task_queue.cpp.s:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/task_queue.cpp.s
.PHONY : src/task_queue.cpp.s

src/util/ring_buffer.o: src/util/ring_buffer.cpp.o

.PHONY : src/util/ring_buffer.o

# target to build an object file
src/util/ring_buffer.cpp.o:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/util/ring_buffer.cpp.o
.PHONY : src/util/ring_buffer.cpp.o

src/util/ring_buffer.i: src/util/ring_buffer.cpp.i

.PHONY : src/util/ring_buffer.i

# target to preprocess a source file
src/util/ring_buffer.cpp.i:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/util/ring_buffer.cpp.i
.PHONY : src/util/ring_buffer.cpp.i

src/util/ring_buffer.s: src/util/ring_buffer.cpp.s

.PHONY : src/util/ring_buffer.s

# target to generate assembly for a file
src/util/ring_buffer.cpp.s:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/util/ring_buffer.cpp.s
.PHONY : src/util/ring_buffer.cpp.s

src/util/time_wheel.o: src/util/time_wheel.cpp.o

.PHONY : src/util/time_wheel.o

# target to build an object file
src/util/time_wheel.cpp.o:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/util/time_wheel.cpp.o
.PHONY : src/util/time_wheel.cpp.o

src/util/time_wheel.i: src/util/time_wheel.cpp.i

.PHONY : src/util/time_wheel.i

# target to preprocess a source file
src/util/time_wheel.cpp.i:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/util/time_wheel.cpp.i
.PHONY : src/util/time_wheel.cpp.i

src/util/time_wheel.s: src/util/time_wheel.cpp.s

.PHONY : src/util/time_wheel.s

# target to generate assembly for a file
src/util/time_wheel.cpp.s:
	$(MAKE) -f CMakeFiles/tcp.dir/build.make CMakeFiles/tcp.dir/src/util/time_wheel.cpp.s
.PHONY : src/util/time_wheel.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... tcp"
	@echo "... src/buffer/cmd_buffer.o"
	@echo "... src/buffer/cmd_buffer.i"
	@echo "... src/buffer/cmd_buffer.s"
	@echo "... src/buffer/header_buffer.o"
	@echo "... src/buffer/header_buffer.i"
	@echo "... src/buffer/header_buffer.s"
	@echo "... src/global/global.o"
	@echo "... src/global/global.i"
	@echo "... src/global/global.s"
	@echo "... src/listener.o"
	@echo "... src/listener.i"
	@echo "... src/listener.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sender.o"
	@echo "... src/sender.i"
	@echo "... src/sender.s"
	@echo "... src/task_queue.o"
	@echo "... src/task_queue.i"
	@echo "... src/task_queue.s"
	@echo "... src/util/ring_buffer.o"
	@echo "... src/util/ring_buffer.i"
	@echo "... src/util/ring_buffer.s"
	@echo "... src/util/time_wheel.o"
	@echo "... src/util/time_wheel.i"
	@echo "... src/util/time_wheel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

